create table if not exists public.lianliankan_scores (
  id bigint generated by default as identity primary key,
  difficulty text not null check (difficulty in ('easy', 'normal', 'hard')),
  nickname text not null check (char_length(trim(nickname)) between 1 and 12),
  nickname_key text not null check (nickname_key = lower(trim(nickname_key))),
  seconds integer not null check (seconds >= 0),
  moves integer not null check (moves >= 0),
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (difficulty, nickname_key)
);

create index if not exists lianliankan_scores_rank_idx
  on public.lianliankan_scores (difficulty, seconds, moves);

alter table public.lianliankan_scores enable row level security;

drop policy if exists "Scores are visible to everyone" on public.lianliankan_scores;
create policy "Scores are visible to everyone"
  on public.lianliankan_scores
  for select
  to anon
  using (true);

drop policy if exists "Anyone can add scores" on public.lianliankan_scores;
create policy "Anyone can add scores"
  on public.lianliankan_scores
  for insert
  to anon
  with check (true);

drop policy if exists "Anyone can improve a score" on public.lianliankan_scores;
create policy "Anyone can improve a score"
  on public.lianliankan_scores
  for update
  to anon
  using (true)
  with check (true);

create table if not exists public.lianliankan_feedback (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(trim(nickname)) between 1 and 12),
  nickname_key text not null check (nickname_key = lower(trim(nickname_key))),
  difficulty text not null check (difficulty in ('easy', 'normal', 'hard')),
  level integer not null check (level between 1 and 99),
  message text not null check (char_length(trim(message)) between 1 and 200),
  created_at timestamptz not null default now()
);

create index if not exists lianliankan_feedback_created_at_idx
  on public.lianliankan_feedback (created_at desc);

alter table public.lianliankan_feedback enable row level security;

drop policy if exists "Anyone can add feedback" on public.lianliankan_feedback;
create policy "Anyone can add feedback"
  on public.lianliankan_feedback
  for insert
  to anon
  with check (true);
